apiVersion: v1
kind: Service
metadata:
  name: bulut-bilisim-servis
spec:
  selector:
    name: bulut-bilisim-proje-servis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer
